export const PLAN_LIMITS = {
  free: {
    name: "Free",
    price: "$0",
    priceAmount: 0,
    maxUploadDurationSeconds: 1800,
    monthlyProcessingMinutes: 45,
    exportMaxHeight: 720,
    label: "30 min/video",
    features: [
      "Upload videos up to 30 minutes",
      "45 minutes processing / month",
      "AI viral clip detection",
      "Smart AI reframing",
      "Auto captions",
      "Watermarked exports (720p)",
      "3-day video storage",
    ],
  },
  creator: {
    name: "Creator",
    price: "$15",
    priceAmount: 15,
    maxUploadDurationSeconds: 7200,
    monthlyProcessingMinutes: 300,
    exportMaxHeight: 1080,
    label: "2 hours/video",
    popular: true,
    features: [
      "Upload videos up to 2 hours",
      "300 minutes processing / month",
      "No watermark",
      "1080p Full HD exports",
      "All dynamic caption styles",
      "AI viral clip detection & hook scoring",
      "Smart AI auto-reframing",
      "Permanent video storage",
      "Fast rendering queue",
    ],
  },
  power: {
    name: "Power",
    price: "$49",
    priceAmount: 49,
    maxUploadDurationSeconds: 7200,
    monthlyProcessingMinutes: 600,
    exportMaxHeight: 1080,
    label: "2 hours/video",
    features: [
      "Upload videos up to 2 hours",
      "600 minutes processing / month",
      "No watermark",
      "1080p HD exports",
      "Premium caption styles",
      "Advanced AI reframing",
      "Unlimited clips from processed videos",
      "Permanent video storage",
      "Priority processing queue",
    ],
  },
} as const;

export type PlanName = keyof typeof PLAN_LIMITS;

export function getPlanLimit(planName?: string | null) {
  let normalized = (planName || "free").trim().toLowerCase();
  if (normalized.includes("power")) {
    normalized = "power";
  } else if (normalized.includes("creator")) {
    normalized = "creator";
  }
  const key = normalized as PlanName;
  return PLAN_LIMITS[key] || PLAN_LIMITS.free;
}

export const LANGUAGES = [
  { name: "Global English", code: "en" },
  { name: "Australian English", code: "en_au" },
  { name: "British English", code: "en_uk" },
  { name: "US English", code: "en_us" },
  { name: "Spanish", code: "es" },
  { name: "French", code: "fr" },
  { name: "German", code: "de" },
  { name: "Italian", code: "it" },
  { name: "Portuguese", code: "pt" },
  { name: "Dutch", code: "nl" },
  { name: "Hindi", code: "hi" },
  { name: "Japanese", code: "ja" },
  { name: "Chinese", code: "zh" },
  { name: "Finnish", code: "fi" },
  { name: "Korean", code: "ko" },
  { name: "Polish", code: "pl" },
  { name: "Russian", code: "ru" },
  { name: "Turkish", code: "tr" },
  { name: "Ukrainian", code: "uk" },
  { name: "Vietnamese", code: "vi" },
  { name: "Afrikaans", code: "af" },
  { name: "Albanian", code: "sq" },
  { name: "Amharic", code: "am" },
  { name: "Arabic", code: "ar" },
  { name: "Armenian", code: "hy" },
  { name: "Assamese", code: "as" },
  { name: "Azerbaijani", code: "az" },
  { name: "Basque", code: "eu" },
  { name: "Belarusian", code: "be" },
  { name: "Bengali", code: "bn" },
  { name: "Bosnian", code: "bs" },
  { name: "Bulgarian", code: "bg" },
  { name: "Catalan", code: "ca" },
  { name: "Croatian", code: "hr" },
  { name: "Czech", code: "cs" },
  { name: "Danish", code: "da" },
  { name: "Estonian", code: "et" },
  { name: "Galician", code: "gl" },
  { name: "Georgian", code: "ka" },
  { name: "Greek", code: "el" },
  { name: "Gujarati", code: "gu" },
  { name: "Haitian", code: "ht" },
  { name: "Hausa", code: "ha" },
  { name: "Hawaiian", code: "haw" },
  { name: "Hebrew", code: "he" },
  { name: "Hungarian", code: "hu" },
  { name: "Icelandic", code: "is" },
  { name: "Indonesian", code: "id" },
  { name: "Javanese", code: "jw" },
  { name: "Kannada", code: "kn" },
  { name: "Kazakh", code: "kk" },
  { name: "Lao", code: "lo" },
  { name: "Latin", code: "la" },
  { name: "Latvian", code: "lv" },
  { name: "Lithuanian", code: "lt" },
  { name: "Luxembourgish", code: "lb" },
  { name: "Macedonian", code: "mk" },
  { name: "Malagasy", code: "mg" },
  { name: "Malay", code: "ms" },
  { name: "Malayalam", code: "ml" },
  { name: "Maltese", code: "mt" },
  { name: "Maori", code: "mi" },
  { name: "Marathi", code: "mr" },
  { name: "Mongolian", code: "mn" },
  { name: "Nepali", code: "ne" },
  { name: "Norwegian", code: "no" },
  { name: "Panjabi", code: "pa" },
  { name: "Pashto", code: "ps" },
  { name: "Persian", code: "fa" },
  { name: "Romanian", code: "ro" },
  { name: "Serbian", code: "sr" },
  { name: "Shona", code: "sn" },
  { name: "Sindhi", code: "sd" },
  { name: "Sinhala", code: "si" },
  { name: "Slovak", code: "sk" },
  { name: "Slovenian", code: "sl" },
  { name: "Somali", code: "so" },
  { name: "Sundanese", code: "su" },
  { name: "Swahili", code: "sw" },
  { name: "Swedish", code: "sv" },
  { name: "Tagalog", code: "tl" },
  { name: "Tajik", code: "tg" },
  { name: "Tamil", code: "ta" },
  { name: "Telugu", code: "te" },
  { name: "Urdu", code: "ur" },
  { name: "Uzbek", code: "uz" },
  { name: "Welsh", code: "cy" },
  { name: "Yiddish", code: "yi" },
  { name: "Yoruba", code: "yo" },
]

// Cloudflare R2 public assets base URL
const R2_PUBLIC_URL =
  process.env.NEXT_PUBLIC_R2_PUBLIC_URL ||
  "https://pub-dab84dec13074258806f788a00943c46.r2.dev"

// Preview asset paths (rendered on demo portrait image at position 75%, hosted on Cloudflare R2)
export const PREVIEW_IMAGES: Record<string, string> = {
  aliabdlal: `${R2_PUBLIC_URL}/previews/caption_aliabdlal_v2.jpg`,
  unbox: `${R2_PUBLIC_URL}/previews/caption_unbox_v2.jpg`,
  billy: `${R2_PUBLIC_URL}/previews/caption_billy_v2.jpg`,
  sara: `${R2_PUBLIC_URL}/previews/caption_sara_v2.jpg`,
  fred: `${R2_PUBLIC_URL}/previews/caption_fred_v2.jpg`,
  casey: `${R2_PUBLIC_URL}/previews/caption_casey_v2.jpg`,
  tom: `${R2_PUBLIC_URL}/previews/caption_tom_v2.jpg`,
  bobby: `${R2_PUBLIC_URL}/previews/caption_bobby_v2.jpg`,
  podcast: `${R2_PUBLIC_URL}/previews/caption_podcast_v2.jpg`,
  badge: `${R2_PUBLIC_URL}/previews/caption_badge_v2.jpg`,
  luxury: `${R2_PUBLIC_URL}/previews/caption_luxury_v2.jpg`,
  neon: `${R2_PUBLIC_URL}/previews/caption_neon_v2.jpg`,
  focus: `${R2_PUBLIC_URL}/previews/caption_focus_v2.jpg`,
  cinema: `${R2_PUBLIC_URL}/previews/caption_cinema_v2.jpg`,
  creator: `${R2_PUBLIC_URL}/previews/caption_creator_v2.jpg`,
  minimal: `${R2_PUBLIC_URL}/previews/caption_minimal_v2.jpg`,
  sticker: `${R2_PUBLIC_URL}/previews/caption_sticker_v2.jpg`,
  coral: `${R2_PUBLIC_URL}/previews/caption_coral_v2.jpg`,
  growth: `${R2_PUBLIC_URL}/previews/caption_growth_v2.jpg`,
  hormozi: `${R2_PUBLIC_URL}/previews/caption_hormozi_v2.jpg`,
  impact: `${R2_PUBLIC_URL}/previews/caption_impact_v2.jpg`,
}

// Hover video preview paths (~100-120KB WebM loops hosted on Cloudflare R2)
export const PREVIEW_VIDEOS: Record<string, string> = {
  aliabdlal: `${R2_PUBLIC_URL}/previews/caption_aliabdlal_v2.webm`,
  unbox: `${R2_PUBLIC_URL}/previews/caption_unbox_v2.webm`,
  billy: `${R2_PUBLIC_URL}/previews/caption_billy_v2.webm`,
  sara: `${R2_PUBLIC_URL}/previews/caption_sara_v2.webm`,
  fred: `${R2_PUBLIC_URL}/previews/caption_fred_v2.webm`,
  casey: `${R2_PUBLIC_URL}/previews/caption_casey_v2.webm`,
  tom: `${R2_PUBLIC_URL}/previews/caption_tom_v2.webm`,
  bobby: `${R2_PUBLIC_URL}/previews/caption_bobby_v2.webm`,
  podcast: `${R2_PUBLIC_URL}/previews/caption_podcast_v2.webm`,
  badge: `${R2_PUBLIC_URL}/previews/caption_badge_v2.webm`,
  luxury: `${R2_PUBLIC_URL}/previews/caption_luxury_v2.webm`,
  neon: `${R2_PUBLIC_URL}/previews/caption_neon_v2.webm`,
  focus: `${R2_PUBLIC_URL}/previews/caption_focus_v2.webm`,
  cinema: `${R2_PUBLIC_URL}/previews/caption_cinema_v2.webm`,
  creator: `${R2_PUBLIC_URL}/previews/caption_creator_v2.webm`,
  minimal: `${R2_PUBLIC_URL}/previews/caption_minimal_v2.webm`,
  sticker: `${R2_PUBLIC_URL}/previews/caption_sticker_v2.webm`,
  coral: `${R2_PUBLIC_URL}/previews/caption_coral_v2.webm`,
  growth: `${R2_PUBLIC_URL}/previews/caption_growth_v2.webm`,
  hormozi: `${R2_PUBLIC_URL}/previews/caption_hormozi_v2.webm`,
  impact: `${R2_PUBLIC_URL}/previews/caption_impact_v2.webm`,
}